---
abstract: 'guess an appropriate column type for a set of data'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  Data::Dumper: '0'
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SQL-Type-Guess
no_index:
  directory:
    - t
    - inc
requires:
  File::Glob: '0'
  Pod::Usage: '0'
  Spreadsheet::Read: '0'
  Text::CleanFragment: '0'
  perl: '5.008'
  strict: '0'
  warnings: '0'
resources:
  repository: git://github.com/Corion/SQL-Type-Guess.git
version: '0.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
